const Prompt = require('../models/Prompt');
const { GoogleGenerativeAI } = require('@google/generative-ai');

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);


exports.createImage = async (req, res) => {
    try {
        const { prompt, negativePrompt, style } = req.body;
        const userId = req.user?.id;
        if (!userId) {
            return res.status(401).json({ success: false, message: 'Unauthorized' });
        }

        if (!process.env.GEMINI_API_KEY) {
            return res.status(500).json({ success: false, message: 'Gemini API Key missing' });
        }

        // 1. Use Gemini to enhance the prompt and generate a short story/description
        const model = genAI.getGenerativeModel({ model: "gemini-1.5-pro" });


        const improvementPrompt = `
      Act as an expert AI Art prompt engineer. 
      User Input: "${prompt}"
      Style: "${style}"
      
      Task 1: Create a highly detailed, descriptive prompt (max 200 chars) optimized for Stable Diffusion based on the input.
      Task 2: Write a very short, creative 1-sentence caption or story for this image.

      Return ONLY a JSON object like this:
      {
        "enhancedPrompt": "...",
        "caption": "..."
      }
    `;

        const result = await model.generateContent(improvementPrompt);
        const response = await result.response;
        const text = response.text();

        // Parse JSON (handle potential markdown ticks)
        let aiData;
        try {
            const cleanText = text.replace(/```json/g, '').replace(/```/g, '').trim();
            aiData = JSON.parse(cleanText);
        } catch (e) {
            aiData = { enhancedPrompt: prompt, caption: "Generated by AI" }; // Fallback
        }

        // 2. Generate Real Image using Pollinations.ai (Free, Fast, No Key needed for image part)
        // We use the ENHANCED prompt for better results
        const finalPrompt = aiData.enhancedPrompt || prompt;
        const encodedPrompt = encodeURIComponent(finalPrompt + ", " + style + ", high quality, 8k");
        const imageUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}?nologo=true&private=true&enhance=false`;

        const newPrompt = new Prompt({
            prompt,
            enhancedPrompt: finalPrompt,
            aiResponse: aiData.caption,
            negativePrompt,
            style,
            imageUrl: imageUrl, // Real URL
            user: userId,
        });

        await newPrompt.save();

        res.status(201).json({ success: true, data: newPrompt });
    } catch (error) {
        console.error('Error creating image:', error);
        res.status(500).json({ success: false, error: 'Server Error' });
    }
};

exports.getPrompts = async (req, res) => {
    try {
        const prompts = await Prompt.find().sort({ createdAt: -1 });
        res.status(200).json({ success: true, data: prompts });
    } catch (error) {
        console.error('Error fetching prompts:', error);
        res.status(500).json({ success: false, error: 'Server Error' });
    }
};

exports.generateText = async (req, res) => {
    try {
        const { prompt, style } = req.body;
        if (!prompt) {
            return res.status(400).json({ success: false, message: 'Prompt is required' });
        }

        if (!process.env.GEMINI_API_KEY) {
            return res.status(500).json({ success: false, message: 'Gemini API Key missing' });
        }

        const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
        const textPrompt = `
      Act as a creative assistant.
      User Prompt: "${prompt}"
      Style: "${style || 'Realistic'}"

      Write a concise, vivid 2-3 sentence response describing the scene.
    `;

        const result = await model.generateContent(textPrompt);
        const response = await result.response;
        const text = response.text();

        res.status(200).json({ success: true, data: { prompt, aiResponse: text.trim() } });
    } catch (error) {
        console.error('Error generating text:', error);
        res.status(500).json({ success: false, error: 'Server Error' });
    }
};

exports.getUserPrompts = async (req, res) => {
    try {
        const prompts = await Prompt.find({ user: req.user.id }).sort({ createdAt: -1 });
        res.status(200).json({ success: true, data: prompts });
    } catch (error) {
        console.error('Error fetching user prompts:', error);
        res.status(500).json({ success: false, error: 'Server Error' });
    }
};
