const mongoose = require('mongoose');

const promptSchema = new mongoose.Schema({
  prompt: {
    type: String,
    required: true,
  },
  enhancedPrompt: {
    type: String,
  },
  aiResponse: {
    type: String, // The story or explanation generated by Gemini
  },
  negativePrompt: {
    type: String,
    default: '',
  },
  style: {
    type: String,
    default: 'Realistic',
  },
  imageUrl: {
    type: String,
  },
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  conversation: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Conversation',
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

module.exports = mongoose.model('Prompt', promptSchema);
